/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // UDEE Brand Colors
        "outline":                    "#81756e",
        "surface-dim":                "#dfd9d6",
        "surface-tint":               "#705a4c",
        "inverse-surface":            "#33302e",
        "background":                 "#fff8f5",
        "outline-variant":            "#d2c4bc",
        "on-primary-fixed":           "#28180d",
        "tertiary-container":         "#3f2b0f",
        "tertiary":                   "#281600",
        "on-tertiary":                "#ffffff",
        "inverse-primary":            "#dec1af",
        "on-primary-fixed-variant":   "#574335",
        "primary-fixed":              "#fbddca",
        "on-error-container":         "#93000a",
        "surface-container-highest":  "#e8e1df",
        "on-primary":                 "#ffffff",
        "on-secondary-fixed-variant": "#643e1b",
        "on-surface-variant":         "#4f453f",
        "surface":                    "#fff8f5",
        "error-container":            "#ffdad6",
        "tertiary-fixed":             "#ffddb6",
        "secondary-fixed-dim":        "#f3bc8e",
        "primary-container":          "#3d2b1f",
        "on-tertiary-container":      "#b0916d",
        "on-tertiary-fixed":          "#291801",
        "surface-container-high":     "#eee7e4",
        "on-tertiary-fixed-variant":  "#5a4224",
        "surface-variant":            "#e8e1df",
        "surface-bright":             "#fff8f5",
        "surface-container-lowest":   "#ffffff",
        "secondary-fixed":            "#ffdcc1",
        "surface-container-low":      "#f9f2f0",
        "on-secondary":               "#ffffff",
        "surface-container":          "#f3ecea",
        "on-primary-container":       "#ac9181",
        "on-background":              "#1d1b1a",
        "error":                      "#ba1a1a",
        "on-secondary-container":     "#7a512c",
        "tertiary-fixed-dim":         "#e3c199",
        "on-error":                   "#ffffff",
        "secondary":                  "#7f5530",
        "inverse-on-surface":         "#f6efed",
        "on-surface":                 "#1d1b1a",
        "secondary-container":        "#ffc698",
        "primary":                    "#26170c",
        "primary-fixed-dim":          "#dec1af",
        "on-secondary-fixed":         "#2e1500",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        xs:   "4px",
        sm:   "8px",
        md:   "12px",
        base: "16px",
        lg:   "24px",
        xl:   "32px",
        xxl:  "48px",
        huge: "64px",
      },
      fontFamily: {
        prompt: ["Prompt", "sans-serif"],
        inter:  ["Inter",  "sans-serif"],
        kanit:  ["Kanit",  "sans-serif"],
        mitr:   ["Mitr",   "sans-serif"],
      },
      fontSize: {
        "display-lg":        ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md":       ["32px", { lineHeight: "1.3", fontWeight: "500" }],
        "title-lg":          ["24px", { lineHeight: "1.4", fontWeight: "500" }],
        "title-md":          ["20px", { lineHeight: "1.5", fontWeight: "500" }],
        "body-lg":           ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md":           ["14px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm":          ["12px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}