services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: udee_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: udee1234
      MYSQL_DATABASE: udee
    ports:
      - "3307:3306"
    volumes:
      - udee_db_data:/var/lib/mysql

  # Backend
  backend:
    build: ./backend
    container_name: udee_backend
    restart: always
    ports:
      - "5001:5000"
    environment:
      DATABASE_URL: "mysql://root:udee1234@db:3306/udee"
      JWT_SECRET: "udee1234"
      PORT: 5000
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/generated

  # Frontend
  frontend:
    build: ./frontend
    container_name: udee_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:5001/api
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  udee_db_data:
